version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "package.json" }}
  deploy:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - run: git config user.name $GITHUB_EMAIL
      - run: git config user.email $GITHUB_NAME
      - run: yarn generate
      - run: yarn deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: gh-pages